# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fun1 <- function(A) {
    .Call('_first_fun1', PACKAGE = 'first', A)
}

fun2 <- function(A) {
    .Call('_first_fun2', PACKAGE = 'first', A)
}

